export enum DefaultAnimations {
  Idle = 'Idle',
  DropIdle = 'DropIdle',
  DropRolling = 'DropRolling',
  DropRunning = 'DropRunning',
  Falling = 'Falling',
  IdleRotateLeft = 'IdleRotateLeft',
  IdleRotateRight = 'IdleRotateRight',
  JumpIdle =  'JumpIdle',
  JumpRunning = 'JumpRunning',
  // StartWalkingForward =  'start_walk_forward',
  // StartWalkingLeft = 'start_walk_left',
  // StartWalkingRight = 'start_walk_right',
  // StartWalkingBackLeft = 'start_walk_back_left',
  // StartWalkingBackRight = 'start_walk_back_right',
  Walk = 'Walk',
  // EndWalk = 'end_walk',
  Sprint = 'Sprint',
}
