export enum DefaultAnimations {
  Idle = 'idle',
  DropIdle = 'drop_idle',
  DropRolling = 'drop_rolling',
  DropRunning = 'drop_running',
  Falling = 'falling',
  IdleRotateLeft = 'idle_rotate_left',
  IdleRotateRight = 'idle_rotate_right',
  JumpIdle =  'jump_idle',
  JumpRunning = 'jump_running',
  // StartWalkingForward =  'start_walk_forward',
  // StartWalkingLeft = 'start_walk_left',
  // StartWalkingRight = 'start_walk_right',
  // StartWalkingBackLeft = 'start_walk_back_left',
  // StartWalkingBackRight = 'start_walk_back_right',
  Walk = 'walk',
  EndWalk = 'end_walk',
  Sprint = 'sprint',
}
