export enum EventTrigger {
  AUTOMATIC = 'AUTOMATIC',
  PARALLEL_PROCESS = 'PARALLEL_PROCESS',
  ON_PLAYER_TOUCH = 'ON_PLAYER_TOUCH',
  ON_EVENT_TOUCH_PLAYER = 'ON_EVENT_TOUCH_PLAYER',
  ON_ACTION_KEY_DOWN = 'ON_ACTION_KEY_DOWN'
}
